FrontEnd.Management/Components/MenuViewComponent.cs
using FrontEnd.Common.Entites.Management;
using FrontEnd.Common.Helpers;
using FrontEnd.Common.Models.Management.User;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FrontEnd.Management.Components
{
    public class MenuViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userData = await HttpContext.Session.GetObjectFromJson<UserInfoWithMenuModel>(Constants.STATIC_USERMODEL);
            return View(userData);
        } 
    }
}

FrontEnd.Management/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FrontEnd.Common.Core.Security.Crypt;
using FrontEnd.Common.Entites.Management;
using FrontEnd.Common.Helpers;
using FrontEnd.Common.Models.Management.Login;
using FrontEnd.Common.Models.Management.User;
using FrontEnd.Common.Services.Login;
using FrontEnd.Common.Services.User; 
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace FrontEnd.Management.Controllers
{
    public class LoginController : Controller
    {
        protected IConfiguration _baseConfig;
        private ILoginService loginService;
        private IUserService _user;
        public LoginController(IConfiguration configuration, ILoginService _loginService, IUserService user)
        {
            loginService = _loginService;
            _user = user;
            _baseConfig = configuration;
        }
        public IActionResult Index(string referrer = "")
        {
            ViewBag.ApiUrl = _baseConfig[Constants.STATIC_ApiUrl_URL];
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> LoginPost([FromBody]LoginModel req)
        {
            try
            {
                req.UserName = req.UserName.Trim().ToLower();
                req.Password = Md5.GetMD5Hash(req.Password.Trim());
                var responce = await loginService.LoginPost(req.ToObject());
                if (responce != null && responce.Result == 1)
                {
                    var model = new GetUserInfoWithMenuQuery { AppID = 1};//(int)LMS.Common.Constants.Menu_AppID.Admin 
                    var getUserInfoWithMenu = await loginService.GetUserInfoWithMenu(model, responce.Data.Token);
                    if (getUserInfoWithMenu != null && getUserInfoWithMenu.Result == 1 && getUserInfoWithMenu.Data != null)
                    { 
                        getUserInfoWithMenu.Data.Token = responce.Data.Token;
                        getUserInfoWithMenu.Data.TimeExpired = responce.Data.TimeExpired;
                        // getUserInfoWithMenu.Data.TimeExpired = DateTime.Now.AddMinutes(Constants.STATIC_DateExpiration_Token); 
                        getUserInfoWithMenu.Data.TimeExpiredString = getUserInfoWithMenu.Data.TimeExpired.ToString("dd/MM/yyyy HH:mm");
                        getUserInfoWithMenu.Data.UserLoginModel = new UserLoginModel
                        {
                            AdminUrl = _baseConfig[Constants.STATIC_HOME_URL],
                            AccountantUrl = _baseConfig[Constants.STATIC_HOME_AccountantUrl],
                            LenderUrl = _baseConfig[Constants.STATIC_HOME_LenderUrl],
                            THNUrl = _baseConfig[Constants.STATIC_HOME_RecoveryOfLoans],
                            PathRereshToken = Constants.STATIC_Path_RereshToken
                        }; 
                        getUserInfoWithMenu.Data.LoginUrl = _baseConfig[Constants.STATIC_Login_URL];
                        getUserInfoWithMenu.Data.ApiUrl = _baseConfig[Constants.STATIC_ApiUrl_URL];
                        getUserInfoWithMenu.Data.AdminUrl = _baseConfig[Constants.STATIC_HOME_URL];
                        getUserInfoWithMenu.Data.DomainCookie = _baseConfig[Constants.STATIC_Cookie];
                        getUserInfoWithMenu.Data.CookieName = Constants.STATIC_USERMODEL;
                        HttpContext.Session.SetObjectAsJson(Constants.STATIC_USERMODEL, getUserInfoWithMenu.Data);
                        var value = getUserInfoWithMenu.Data;
                        value.LstMenu = null;
                        var cookie = JsonConvert.SerializeObject(value);
                        CookieOptions option = new CookieOptions();
                        // option.HttpOnly = false;
                        option.Secure = true;
                        option.Expires = DateTime.Now.AddDays(30);
                        option.Domain = _baseConfig[Constants.STATIC_Cookie];
                        Response.Cookies.Append(Constants.STATIC_USERMODEL, cookie, option); 
                        return Json(new { status = 1, message = "Đăng nhập thành công!", data = JsonConvert.SerializeObject(getUserInfoWithMenu.Data) });
                    }
                }
                return Json(new { status = 0, message = "Thông tin đăng nhập không đúng!" });
            }
            catch (Exception)
            {
                return Json(new { status = 0, message = "Xảy ra lỗi khi đăng nhập. Vui lòng thử lại." });
            } 
        }
        [Route("logout.html")]
        public async Task<IActionResult> Logout()
        {
            var user = await HttpContext.Session.GetObjectFromJson<UserInfoWithMenuModel>(Constants.STATIC_USERMODEL);
            if (user != null && !string.IsNullOrEmpty(user.Token)) {
                var responce = await loginService.Logout(user);
            } 
            HttpContext.Session.SetObjectAsJson(Constants.STATIC_USERMODEL, null);
            RemoveCookie(Constants.STATIC_USERMODEL);
            RemoveCookie(Constants.STATIC_CALL_INFO_COOKIE); 
            return Redirect(_baseConfig[Constants.STATIC_Login_URL]);
        }
        [Route("redirect")]
        [HttpGet]
        public async Task<IActionResult> RedirectIndex(string token)
        {
            try
            {
                //Validate Token
                if (string.IsNullOrEmpty(token))
                    return Redirect(_baseConfig[Constants.STATIC_Login_URL]);
                var user = await _user.GetUserByUserID(token, 1);
                var users = new UserLoginModel { UserID = user.UserID, UserName = user.UserName,FullName = user.FullName, Token = token };
                HttpContext.Session.SetObjectAsJson(Constants.STATIC_USERMODEL, users); 
                return Redirect(Constants.STATIC_HOME_URL);
            }
            catch (Exception)
            {
                return Redirect(_baseConfig[Constants.STATIC_Login_URL]);
            }
        }
        public void SetCookie(string key, string value, int? expireTime)
        {
            CookieOptions option = new CookieOptions();
            if (expireTime.HasValue)
                option.Expires = DateTime.Now.AddHours(expireTime.Value);
            else
                option.Expires = DateTime.Now.AddHours(12);
            Response.Cookies.Append(key, value, option);
        }
        public void RemoveCookie(string key)
        { 
            Response.Cookies.Delete(key);
        }
    }
}

FrontEnd.Management/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration  
@{
    var AdminUrl = Configuration["AppSettings:AdminUrl"];
    var CookieName = FrontEnd.Common.Helpers.Constants.STATIC_USERMODEL;
}
<!DOCTYPE html>
<html lang="en">

<!-- begin::Head -->
<head>
    <base href="">
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="description" content="Updates and statistics">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    @* <meta name="viewport" content="width=@(isMobile?"1400px":"device-width")">*@

    <!--begin::Fonts -->
    @*<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">*@
    <link href="@AdminUrl/assets/plugins/custom/jstree/jstree.bundle.css" rel="stylesheet" />
    <!--end::Fonts -->
    <!--begin::Page Vendors Styles(used by this page) -->
    <link href="@AdminUrl/assets/plugins/custom/fullcalendar/fullcalendar.bundle.css" rel="stylesheet" type="text/css" />

    <!--end::Page Vendors Styles -->
    <!--begin::Global Theme Styles(used by all pages) -->
    <link href="@AdminUrl/assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
    <link href="@AdminUrl/assets/css/style.bundle.css" rel="stylesheet" type="text/css" />

    <!--end::Global Theme Styles -->
    <!--begin::Layout Skins(used by all pages) -->
    <link href="@AdminUrl/assets/css/skins/header/base/light.min.css" rel="stylesheet" type="text/css" />
    <link href="@AdminUrl/assets/css/skins/header/menu/light.min.css" rel="stylesheet" type="text/css" />
    <link href="@AdminUrl/assets/css/skins/brand/dark.min.css" rel="stylesheet" type="text/css" />
    <link href="@AdminUrl/assets/css/skins/aside/dark.min.css" rel="stylesheet" type="text/css" />
    <link href="/css/customize.css" rel="stylesheet" />

    <link href="~/kendoUi/styles/lms.css" rel="stylesheet" />
    @*đánh giá bằng sao css*@
    <link href="~/css/ratestar.css" rel="stylesheet" />
    <!--end::Layout Skins -->
    @*<link rel="shortcut icon" href="~/img/logo.png" />*@
    <link rel="shortcut icon" href="~/assets/media/logos/favicon.ico" type="image/x-icon" />
    <!-- Start of  Zendesk Widget script -->
    @*<script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=4c0f4594-939a-4897-a115-28917de074c9"></script>*@
    <!-- End of  Zendesk Widget script -->
<script type="text/javascript">
        var ApiUrl = '@Configuration["Configuration:ApiUrl"]';
        var LoginUrl = '@Configuration["AppSettings:Login"]';
        var  STATIC_USERMODEL = '@CookieName';
    @*var userModel = JSON.stringify('@ViewBag.UserModel');
    
    createCookie("USERMODEL2", "dnv", -1);
    function createCookie (name, value, days) {
        if (days) {
            var date = new Date();
            date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
            var expires = "; expires=" + date.toGMTString();
        }
        else var expires = "";
        document.cookie = name + "=" + value + expires + "; path=/";
    };*@

</script>
</head>

<!-- end::Head -->
<!-- begin::Body -->
<body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-aside--enabled kt-aside--fixed kt-page--loading" style="font-family:Verdana">

    <!-- begin:: Page -->
    <!-- begin:: Header Mobile -->
    <partial name="~/Views/Shared/partials/_header/_base_mobile.cshtml" />

    <!-- end:: Header Mobile -->
    <div class="kt-grid kt-grid--hor kt-grid--root">
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">

            <!-- begin:: Aside -->
            <!-- Uncomment this to display the close button of the panel
            <button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
            -->
            <div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">

                <!-- begin:: Aside -->
                <partial name="~/Views/Shared/partials/_aside/_brand.cshtml" />

                <!-- end:: Aside -->
                <!-- begin:: Aside Menu
                <partial name="~/Views/Shared/partials/_aside/_menu.cshtml" />-->
                @await Component.InvokeAsync("Menu")

                <!-- end:: Aside Menu -->
            </div>

            <!-- end:: Aside -->
            <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">

                <!-- begin:: Header -->
                <div id="kt_header" class="kt-header kt-grid__item  kt-header--fixed ">

                    <!-- begin:: Header Menu -->
                    <!-- Uncomment this to display the close button of the panel
                    <button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
                     -->
                    <partial name="~/Views/Shared/partials/_header/_menu.cshtml" />

                    <!-- end:: Header Menu -->
                    <!-- begin:: Header Topbar -->
                    <partial name="~/Views/Shared/partials/_header/topbar/_base.cshtml" />

                    <!-- end:: Header Topbar -->
                </div>

                <!-- end:: Header -->
                <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">
                    @RenderBody()
                </div>

                <!-- begin:: Footer -->
                <partial name="~/Views/Shared/partials/_footer/_base.cshtml" />

                <!-- end:: Footer -->
            </div>
        </div>
    </div>

    <!-- end:: Page -->
    <!-- begin::Quick Panel -->
    <partial name="~/Views/Shared/partials/_quick_panel.cshtml" />

    <!-- end::Quick Panel -->
    <!-- begin::Scrolltop -->
    <div id="kt_scrolltop" class="kt-scrolltop">
        <i class="fa fa-arrow-up"></i>
    </div>

    <!-- end::Scrolltop -->
    <!-- begin::Global Config(global config for global JS sciprts) -->
    <script>
        var KTAppOptions = {
            "colors": {
                "state": {
                    "brand": "#5d78ff",
                    "dark": "#282a3c",
                    "light": "#ffffff",
                    "primary": "#5867dd",
                    "success": "#34bfa3",
                    "info": "#36a3f7",
                    "warning": "#ffb822",
                    "danger": "#fd3995"
                },
                "base": {
                    "label": [
                        "#c5cbe3",
                        "#a1a8c3",
                        "#3d4465",
                        "#3e4466"
                    ],
                    "shape": [
                        "#f0f3ff",
                        "#d9dffa",
                        "#afb4d4",
                        "#646c9a"
                    ]
                }
            }
        };
    </script>
    <style>
        html, body {
            font-size: 12px !important;
        }
    </style>

    <!-- end::Global Config -->
    <!--begin::Global Theme Bundle(used by all pages) -->


    <script src="@AdminUrl/assets/plugins/global/plugins.bundle.js" type="text/javascript"></script>
    <script src="@AdminUrl/assets/js/scripts.bundle.js" type="text/javascript"></script>
    <script src="@AdminUrl/scripts/configDatatable/translate.js"></script>
    <script src="@AdminUrl/scripts/libraryConfig/datepicker-vi.js"></script>
    <script src="@AdminUrl/scripts/Lib.js"></script>
    <script src="@AdminUrl/js/jquery.cookie.js"></script>

    <script src="@AdminUrl/kendoUi/js/jszip.min.js"></script>
    <script src="@AdminUrl/kendoUi/js/kendo.all.min.js"></script>
    <script src="@AdminUrl/js/jstree.min.js" type="text/javascript"></script>
    <script src="@AdminUrl/assets/js/pages/crud/forms/widgets/bootstrap-switch.min.js" type="text/javascript"></script>

    <script src="@AdminUrl/js/baseCommon.js?t=@FrontEnd.Common.Helpers.Constants.STATIC_VERSION"></script>

    <!--end::Page Scripts -->
    @RenderSection("Scripts", required: false)
</body>

<!-- end::Body -->
</html>
<script type="text/javascript">
    $(document).ready(function () {
        $(".kt-select2").select2({
            placeholder: "Chọn giá trị"
        });
        $("input").attr("autocomplete", "off");   
    });
</script>

FrontEnd.Management/Views/Shared/_Login.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
@{
    var AdminUrl = Configuration["AppSettings:AdminUrl"]; 
    var CookieName = FrontEnd.Common.Helpers.Constants.STATIC_USERMODEL;
    Layout = null;
}
<!DOCTYPE html>

<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 4 & Angular 8
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<html lang="en">

<!-- begin::Head -->
<head>
    <base href="../../../">
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="description" content="Login page">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--begin::Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">

    <!--end::Fonts -->
    <!--begin::Page Custom Styles(used by this page) -->
    <link href="assets/css/pages/login/login-3.css" rel="stylesheet" type="text/css" />

    <!--end::Page Custom Styles -->
    <!--begin::Global Theme Styles(used by all pages) -->
    <link href="@AdminUrl/assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
    <link href="@AdminUrl/assets/css/style.bundle.css" rel="stylesheet" type="text/css" />

    <!--end::Global Theme Styles -->
    <!--begin::Layout Skins(used by all pages) -->
    <link href="@AdminUrl/assets/css/skins/header/base/light.css" rel="stylesheet" type="text/css" />
    <link href="@AdminUrl/assets/css/skins/header/menu/light.css" rel="stylesheet" type="text/css" />
    <link href="@AdminUrl/assets/css/skins/brand/dark.css" rel="stylesheet" type="text/css" />
    <link href="@AdminUrl/assets/css/skins/aside/dark.css" rel="stylesheet" type="text/css" />

    <!--end::Layout Skins -->
    <link rel="shortcut icon" href="~/assets/media/logos/favicon.ico" />
    <script type="text/javascript">

        var ApiUrl = '@Configuration["Configuration:ApiUrl"]';
        var LoginUrl = '@Configuration["AppSettings:Login"]';
        var  STATIC_USERMODEL = '@CookieName';
    </script>
</head>

<!-- end::Head -->
<!-- begin::Body -->
<body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--fixed kt-subheader--solid kt-aside--enabled kt-aside--fixed kt-page--loading">

    <!-- begin:: Page -->
    @RenderBody()
    <!-- end:: Page -->
    <!-- begin::Global Config(global config for global JS sciprts) -->
    <script>
        var KTAppOptions = {
            "colors": {
                "state": {
                    "brand": "#5d78ff",
                    "dark": "#282a3c",
                    "light": "#ffffff",
                    "primary": "#5867dd",
                    "success": "#34bfa3",
                    "info": "#36a3f7",
                    "warning": "#ffb822",
                    "danger": "#fd3995"
                },
                "base": {
                    "label": [
                        "#c5cbe3",
                        "#a1a8c3",
                        "#3d4465",
                        "#3e4466"
                    ],
                    "shape": [
                        "#f0f3ff",
                        "#d9dffa",
                        "#afb4d4",
                        "#646c9a"
                    ]
                }
            }
        };
    </script>

    <!-- end::Global Config -->
    <!--begin::Global Theme Bundle(used by all pages) -->
    <script src="@AdminUrl/assets/plugins/global/plugins.bundle.js" type="text/javascript"></script>
    <script src="@AdminUrl/assets/js/scripts.bundle.js" type="text/javascript"></script>
    <script src="~/js/jquery-github/jquery.md5.js"></script>
    <script src="~/js/jquery.cookie.js"></script>
    <script src="@AdminUrl/kendoUi/js/kendo.all.min.js"></script>
    <script src="@AdminUrl/kendoUi/js/jszip.min.js"></script>

    <!--end::Page Scripts -->
    <script src="~/scripts/Lib.js"></script>
    <script src="~/scripts/Login/loginJs.js"></script>
    <!--end::Global Theme Bundle -->
    <!--begin::Page Scripts(used by this page) -->
    <!--end::Page Scripts -->
    @RenderSection("Scripts", required: false)
</body>

<!-- end::Body -->
</html>

<script> 
    jQuery(document).ready(function () {
        STATIC_USERMODEL = '@CookieName';
        LoginJs.init();
    });
</script>